### ISSUE TITLE
Problem with dynamodb caching url in package.json

### ISSUE THREAD

**Issue by CaptainChemist** [Brikl/serverless-apollo-dynamodbcache#1]
I'm running into issues with this repository. The core problem is that the caching dynamodb package that this demo tries to load is actual the url for _this_ repository itself. When I look in list of repos you have on this account, I don't see any other repo that could possibly be correct.

What I think is happening, is that this demo repo should actually be at `Brikl/serverless-apollo-persisted-queries-dynamodb` instead of `Brikl/serverless-apollo-dynamodbcache`. This means that you'd also have to republish the dynamodb caching package to: `https://github.com/Brikl/serverless-apollo-dynamodbcache#version-2`.

Thanks for your help, I'd really love to try this out!

**Comment by MeixnerTobias** [comment]
You are right the package is missing this is not on npm yet let me just add the dynamo cache script to the repo itself. Will update tomorrow.

**Comment by CaptainChemist** [comment]
Perfect, thanks for the fast reply!

**Comment by MeixnerTobias** [comment]
@CaptainChemist Try the lastest version - quick fix to show how it works:
https://github.com/Brikl/serverless-apollo-dynamodbcache/commit/cb9cf9b59fb0d583a78631819a4f80315a537ffc

**Comment by CaptainChemist** [comment]
Thanks so much for the updated code! Unfortunately, while this works great locally, I can't get `GET` graphQL query requests to work either directly querying the api gateway or through cloudfront. The actual reponse back is an EOF, which I think is because it doesn't see a graphQL query.

 The problem seems to be that my query string doesn't make it to the lambda function even though I have `use proxy integration` enabled on the gateway.  Did you need to specifically set query string variables in the method request part of the aspi gateway? Or do I need to manually set anything besides those cloudfront settings?

Thanks again, I really love this contribution to the community!

**Comment by CaptainChemist** [comment]
After looking further this seems to be an issue with the DynamoDBCache class and not with the api gateway. For one, passing an empty string for endpoint when in production causes an error. Omitting the `endpoint` key from the serviceConfigOptions when in production gets past that error, but then gives the error `PersistedQueryNotFoundError: PersistedQueryNotFound`.  I'll report back any additional findings,

**Comment by CaptainChemist** [comment]
I think I got it. The problem was that I used Apollo frontend to create a get request that I then just fired off with Postman. The persisted query hash eventually stopped being valid after a while so the fix was to use the frontend for firing off queries instead of the backend.

With that said, there were a few issues I needed to fix when I deployed it.
1) Give repo dynamodb access
2) babel polyfill line was giving me an error
3) You can't pass in an empty string for endpoint to the dynamoDBCache when in AWS

I have a pull request that fix the issues I was having. Feel free to merge it in if you agree. :) 

Thanks again!

**Comment by MeixnerTobias** [comment]
@CaptainChemist Thanks a lot for your help.
Let me review the PR and merge this weekend.
